---
apiVersion: v2
appVersion: v22.10.2
description: A dead simple static HOMepage for your servER to keep your services on hand, from a simple yaml configuration file.
icon: https://raw.githubusercontent.com/bastienwirtz/homer/main/public/logo.png
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/homer
name: homer
version: 9.0.0
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/bastienwirtz/homer
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Use bjw-s common chart.
    - kind: changed
      description: Upgraded app to 22.10.2
