---
apiVersion: v2
appVersion: 2022.10.5
description: Home Assistant
name: home-assistant
version: 16.1.2
deprecated: true
kubeVersion: ">=1.19.0-0"
keywords:
  - home-assistant
  - hass
  - homeassistant
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/home-assistant
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
sources:
  - https://github.com/home-assistant/home-assistant
  - https://github.com/cdr/code-server
  - https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/home-assistant
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
  - name: postgresql
    version: 12.1.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 11.4.5
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: influxdb
    version: 5.4.15
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `postgresql` chart dependency to version 12.1.13
    - kind: changed
      description: Upgraded `mariadb` chart dependency to version 11.4.5
    - kind: changed
      description: Upgraded `influxdb` chart dependency to version 5.4.15
