{{- include "bjw-s.common.loader.init" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-webhook
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ include "pod-gateway.webhookPort" . }}
      targetPort: http
  selector:
    {{- include "pod-gateway.labels.selectorLabels" . | nindent 4 }}
