{{/* Make sure all variables are set properly */}}
{{- include "bjw-s.common.loader.init" . }}

{{- define "pod-gateway.gateway" -}}
{{ printf "%s.%s.svc.%s" (include "bjw-s.common.lib.chart.names.fullname" .) .Release.Namespace .Values.clusterName }}
{{- end -}}

{{- define "pod-gateway.configmap" -}}
{{ include "bjw-s.common.lib.chart.names.fullname" . }}
{{- end -}}

{{- define "pod-gateway.webhookPort" -}}
8080
{{- end -}}


{{- define "pod-gateway.selfSignedIssuer" -}}
{{ printf "%s-webhook-selfsign" (include "bjw-s.common.lib.chart.names.fullname" .) }}
{{- end -}}

{{- define "pod-gateway.rootCAIssuer" -}}
{{ printf "%s-webhook-ca" (include "bjw-s.common.lib.chart.names.fullname" .) }}
{{- end -}}

{{- define "pod-gateway.rootCACertificate" -}}
{{ printf "%s-webhook-ca" (include "bjw-s.common.lib.chart.names.fullname" .) }}
{{- end -}}

{{- define "pod-gateway.servingCertificate" -}}
{{ printf "%s-webhook-tls" (include "bjw-s.common.lib.chart.names.fullname" .) }}
{{- end -}}


{{- define "pod-gateway.labels.selectorLabels" -}}
app.kubernetes.io/name: {{ include "bjw-s.common.lib.chart.names.name" . }}-webhook
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
