---
apiVersion: v2
appVersion: 1.26.0
description: Vaultwarden is a Bitwarden compatable server in Rust
name: vaultwarden
version: 7.0.0
kubeVersion: ">=1.19.0-0"
keywords:
  - Vaultwarden
  - bitwardenrs
home: "https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/vaultwarden"
icon: "https://sesoodan.sirv.com/bitwarden_rs.png"
sources:
  - https://github.com/dani-garcia/vaultwarden
maintainers:
  - name: Rwaltr
    email: rwalt@pm.me
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
  - name: mariadb
    version: 11.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 12.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `appVersion` to 1.26.0
    - kind: changed
      description: Use bjw-s common chart.
