---
apiVersion: v2
appVersion: latest
description: |
  Admision controller to change the default gateway and DNS server of PODs.
  It is typically used to route PODs through a VPN server.
name: pod-gateway
version: 9.10.0
kubeVersion: ">=1.19.0-0"
keywords:
  - pod-gateway
home: https://github.com/angelnu/charts/tree/master/charts/stable/pod-gateway
sources:
  - https://github.com/angelnu/gateway-admision-controller
  - https://github.com/samip5/pod-gateway
icon: https://kubernetes.io/images/wheel.svg
maintainers:
  - name: samip5
    url: https://github.com/samip5
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.4.0

annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 1.4.0
