---
apiVersion: v2
appVersion: v1.0.2.2592
description: Looks and smells like Sonarr but made for music
name: lidarr
version: 15.0.0
kubeVersion: ">=1.19.0-0"
keywords:
  - lidarr
  - torrent
  - usenet
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/lidarr
icon: https://github.com/lidarr/Lidarr/blob/develop/Logo/512.png?raw=true
sources:
  - https://github.com/Lidarr/Lidarr
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Use bjw-s common chart.
    - kind: changed
      description: Upgraded app to 1.0.2.2592.
