---
apiVersion: v2
appVersion: 0.19.2
description: The to-do app to organize your life
name: vikunja
version: 6.5.0
keywords:
  - vikunja
  - to-do
  - tasks
  - calendar
  - kanban
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/vikunja
icon: https://vikunja.io/images/vikunja-logo.svg
sources:
  - https://kolaente.dev/vikunja/api
  - https://kolaente.dev/vikunja/frontend
  - https://hub.docker.com/r/vikunja/api
  - https://hub.docker.com/r/vikunja/frontend
  - https://vikunja.io/docs/
maintainers:
  - name: auricom
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: postgresql
    version: 11.9.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `postgresql` chart dependency to version 11.9.2
