---
apiVersion: v2
appVersion: 5.10.1
description: Ghost is a blogging and publishing software
name: ghost
version: 3.3.0
kubeVersion: ">=1.19.0-0"
keywords:
  - ghost
  - blogging
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/ghost
icon: https://ghost.org/images/logos/logo-black-1.png
sources:
  - https://github.com/TryGhost/Ghost
  - https://github.com/TryGhost/Ghost-CLI
maintainers:
  - name: samip5
    email: sm+k8s-at-home+git@samip.fi
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: mariadb
    version: 11.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `mariadb` chart dependency to version 11.3.1
