---
apiVersion: v2
appVersion: latest
description: Valheim dedicated gameserver with automatic update and world backup support
name: valheim
version: 4.4.2
deprecated: true
kubeVersion: ">=1.16.0-0"
keywords:
  - valheim
home: https://github.com/samipsolutions/helm-charts/tree/master/charts/stable/valheim
icon: https://raw.githubusercontent.com/lloesche/valheim-server-docker/main/misc/Logo_valheim.png
sources:
  - https://github.com/lloesche/valheim-server-docker
  - https://hub.docker.com/r/lloesche/valheim-server
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
